url: https://mochajs.org
name: mochajs.org
title: Mocha
description: The fun, simple & flexible JavaScript test framework
exclude:
  - node_modules
  - README.md
  - Gemfile*
  - package.json
  - CNAME
  - npm-debug.log*
  - scripts
  - .*
